apiVersion: apps/v1
kind: Deployment
metadata:
  name: make-payment
  namespace: clinicflow
  labels:
    app: make-payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: make-payment
  template:
    metadata:
      labels:
        app: make-payment
    spec:
      containers:
        - name: make-payment
          image: backend-make_payment
          imagePullPolicy: Never
          ports:
            - containerPort: 5008
          env:
            - name: APP_ENV
              value: docker
            - name: INVOICE_SERVICE_URL
              value: http://invoice-service:5003
            - name: PAYMENT_SERVICE_URL
              value: http://payment-service:5004
            - name: RECORDS_SERVICE_URL
              value: https://personal-iipxahjd.outsystemscloud.com/ClinicalRecordServices/rest/RecordsAPI
            - name: PATIENT_SERVICE_URL
              value: https://personal-wv4mxqur.outsystemscloud.com/PatientService/rest/PatientAPI
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: internal-api-key
                  key: INTERNAL_API_KEY
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: guest
            - name: RABBITMQ_PASS
              value: guest
            - name: RABBITMQ_QUEUE
              value: notification.payment.success
            - name: HTTP_TIMEOUT_SECONDS
              value: "8"
            - name: DEFAULT_CURRENCY
              value: sgd
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 5008
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5008
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: make-payment
  namespace: clinicflow
  labels:
    app: make-payment
spec:
  type: ClusterIP
  selector:
    app: make-payment
  ports:
    - port: 5008
      targetPort: 5008
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: make-payment-hpa
  namespace: clinicflow
  labels:
    app: make-payment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: make-payment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
