services:
  postgres:
    image: postgres:16
    container_name: esd-postgres
    env_file:
      - .env.postgres
    environment:
      POSTGRES_DB: esd_db
    ports:
      - "5432:5432"
    volumes:
      - esd_pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clinic -d esd_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - esd-net

  invoice_service:
    build:
      context: .
      dockerfile: services/invoice_service/Dockerfile
    container_name: invoice_service
    env_file:
      - ./services/invoice_service/.env
    environment:
      APP_ENV: docker
    ports:
      - "5003:5003"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - esd-net

  payment_service:
    build:
      context: .
      dockerfile: services/payment_service/Dockerfile
    container_name: payment_service
    env_file:
      - ./services/payment_service/.env
    environment:
      APP_ENV: docker
    ports:
      - "5004:5004"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - esd-net

volumes:
  esd_pgdata:

networks:
  esd-net:
    driver: bridge