services:
  invoice_service:
    build:
      context: .
      dockerfile: services/invoice_service/Dockerfile
    container_name: invoice_service
    env_file:
      - ./services/invoice_service/.env
    environment:
      APP_ENV: docker
    ports:
      - "5003:5000"
    restart: unless-stopped
    networks:
      - esd-net
  drug_service:
      build:
        context: .
        dockerfile: services/drug_catalogue_service/Dockerfile
      container_name: drug_service
      ports:
        - "5001:5001"
      restart: unless-stopped
      networks:
        - esd-net
      environment:
        - DATABASE_URL=postgresql://clinic:clinic@host.docker.internal:5432/esd_db

networks:
  esd-net:
    driver: bridge